# from config import SUMMARY_REDIS_IP_ADDRESS, SUMMARY_REDIS_PORT, DEFAULT_SCRAPE_TTL, SUMMARY_REDIS_PASSWORD
import config

REDIS_IP_ADDRESS = config.SUMMARY_REDIS_IP_ADDRESS
REDIS_PORT = config.SUMMARY_REDIS_PORT
REDIS_PASSWORD = config.SUMMARY_REDIS_PASSWORD

if config.REMOTE_HOST:
    
    REMOTE_REDIS = True
else:
    
    REMOTE_REDIS = False
SCHEDULE_PIPELINE =config.DEFAULT_SCRAPE_TTL
